"""ai/generation.py — FAQ answer generation for FR-017 (real OpenAI API).

Model: gpt-4o-mini (eval/thresholds.yaml config.llm_model) — do not change
without an ADR.

Prompt lives in ai/prompts/faq_answer.md (kept as an editable markdown file
rather than a Python string so prompt changes are reviewable/diffable
independent of code, per loops/ai.loop.yaml's "prompt 변경 → 회귀 평가" trigger).

BR-007 "no evidence" fallback (ADR-007, accepted, pattern B): when the model
judges the retrieved context doesn't actually support an answer, it must
output exactly the sentinel string below and nothing else — this file
detects that and substitutes the fixed, human-approved fallback message
instead of whatever the model produced. See ai/pipeline.py for the second,
retrieval-score-based layer of this same guardrail.
"""
from __future__ import annotations

from pathlib import Path

from ai.llm_client import get_client, load_prompt_section
from ai.retrieval import Hit

PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "faq_answer.md"

LLM_MODEL = "gpt-4o-mini"  # eval/thresholds.yaml config.llm_model

# Mechanism (b): sentinel the LLM must emit when retrieved context doesn't
# actually support answering the question (see ai/prompts/faq_answer.md
# rule 3). This is the *primary* BR-007 no-evidence detector in this
# pipeline — see ai/pipeline.py docstring for why a pure similarity
# threshold alone (mechanism a) was found insufficient during development.
NO_EVIDENCE_SENTINEL = "NO_EVIDENCE"

# How much slack _looks_like_sentinel() gives the model around the bare
# sentinel token before treating a response as "not actually the sentinel"
# (i.e. a real, if short, answer). Covers things like "NO_EVIDENCE.",
# "\"NO_EVIDENCE\"", "`NO_EVIDENCE`" without accidentally swallowing a
# genuinely short real answer that happens to start with unrelated text.
_SENTINEL_SLACK_CHARS = 6

# ADR-007 (accepted, pattern B): "질의를 이해하지 못했습니다/관련 근거를 찾지 못했습니다"
# + FAQ 카테고리(품질/납기/가격/대응력)로 유도. This exact string is what gets
# returned to the user whenever the no-evidence path triggers (both gate
# layers in ai/pipeline.py funnel here) — it is never generated by the LLM,
# it's a fixed, reviewed string, per ADR-007 / task-001.md instructions.
FALLBACK_TEXT = (
    "질의를 이해하지 못했거나 관련 근거를 찾지 못했습니다. "
    "평가 기준 FAQ 카테고리(품질, 납기, 가격, 대응력) 중에서 다시 질문해 주세요."
)

_SYSTEM_PROMPT: str | None = None


def _load_system_prompt() -> str:
    global _SYSTEM_PROMPT
    if _SYSTEM_PROMPT is None:
        _SYSTEM_PROMPT = load_prompt_section(PROMPT_PATH, "System Prompt")
    return _SYSTEM_PROMPT


def _looks_like_sentinel(raw_answer: str) -> bool:
    """Robust check for whether the model emitted the NO_EVIDENCE sentinel.

    Exact string equality (`raw_answer == NO_EVIDENCE_SENTINEL`) is brittle:
    a trailing period, surrounding quotes/backticks, or a stray newline all
    make the model's output miss an exact match, and the raw sentinel token
    would then leak to the end user as if it were a real answer -- a direct
    BR-007 violation in exactly the scenario BR-007 exists to prevent (code
    review finding, T-001).

    Strategy: strip whitespace and common wrapping punctuation/quotes, then
    require the sentinel to be present AND make up nearly the entire
    response (within _SENTINEL_SLACK_CHARS). The length check matters: a
    real answer that happens to mention "NO_EVIDENCE" in passing (unlikely
    but not impossible if a chunk ever quoted this doc) shouldn't be
    swallowed just because the substring is there.
    """
    normalized = raw_answer.strip().strip("`'\"“”‘’.,!?　 \n\t")
    if not normalized:
        return False
    if NO_EVIDENCE_SENTINEL not in normalized:
        return False
    return len(normalized) <= len(NO_EVIDENCE_SENTINEL) + _SENTINEL_SLACK_CHARS


def format_context(hits: list[Hit]) -> str:
    return "\n\n".join(f"[{h.chunk_id}] {h.text}" for h in hits)


def generate_answer(question: str, hits: list[Hit], model: str = LLM_MODEL) -> str:
    """Call gpt-4o-mini to answer `question` grounded only in `hits`.

    Returns either a grounded answer, or FALLBACK_TEXT if the model
    determined (via the NO_EVIDENCE_SENTINEL rule in the prompt) that the
    retrieved context doesn't support an answer.
    """
    client = get_client()
    system_prompt = _load_system_prompt()
    context = format_context(hits)
    user_prompt = f"질문: {question}\n\n제공된 문서 조각:\n{context}"

    resp = client.chat.completions.create(
        model=model,
        temperature=0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    raw_answer = (resp.choices[0].message.content or "").strip()

    if _looks_like_sentinel(raw_answer):
        return FALLBACK_TEXT
    return raw_answer
