"""ai/generation.py — FAQ answer generation for FR-017 (real OpenAI API).

Model: gpt-4o-mini (eval/thresholds.yaml config.llm_model) — do not change
without an ADR.

Prompt lives in ai/prompts/faq_answer.md (kept as an editable markdown file
rather than a Python string so prompt changes are reviewable/diffable
independent of code, per loops/ai.loop.yaml's "prompt 변경 → 회귀 평가" trigger).

BR-007 "no evidence" fallback (ADR-007, accepted, pattern B): when the model
judges the retrieved context doesn't actually support an answer, it must
output exactly the sentinel string below and nothing else — this file
detects that and substitutes the fixed, human-approved fallback message
instead of whatever the model produced. See ai/pipeline.py for the second,
retrieval-score-based layer of this same guardrail.
"""
from __future__ import annotations

import os
import re
from pathlib import Path

from ai.retrieval import Hit

PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "faq_answer.md"

LLM_MODEL = "gpt-4o-mini"  # eval/thresholds.yaml config.llm_model

# Mechanism (b): sentinel the LLM must emit when retrieved context doesn't
# actually support answering the question (see ai/prompts/faq_answer.md
# rule 3). This is the *primary* BR-007 no-evidence detector in this
# pipeline — see ai/pipeline.py docstring for why a pure similarity
# threshold alone (mechanism a) was found insufficient during development.
NO_EVIDENCE_SENTINEL = "NO_EVIDENCE"

# ADR-007 (accepted, pattern B): "질의를 이해하지 못했습니다/관련 근거를 찾지 못했습니다"
# + FAQ 카테고리(품질/납기/가격/대응력)로 유도. This exact string is what gets
# returned to the user whenever the no-evidence path triggers (both gate
# layers in ai/pipeline.py funnel here) — it is never generated by the LLM,
# it's a fixed, reviewed string, per ADR-007 / task-001.md instructions.
FALLBACK_TEXT = (
    "질의를 이해하지 못했거나 관련 근거를 찾지 못했습니다. "
    "평가 기준 FAQ 카테고리(품질, 납기, 가격, 대응력) 중에서 다시 질문해 주세요."
)

_SYSTEM_PROMPT: str | None = None
_client = None


def _get_client():
    global _client
    if _client is None:
        from openai import OpenAI

        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is not set in the environment. "
                "This pipeline calls the real OpenAI API (docs/decisions/ADR-006) and does not fall back to a mock."
            )
        _client = OpenAI(api_key=api_key)
    return _client


def _load_system_prompt() -> str:
    """Extract the '## System Prompt' section body out of
    ai/prompts/faq_answer.md so the prompt text lives in one editable place
    (the .md file) instead of being duplicated into a Python string.
    """
    global _SYSTEM_PROMPT
    if _SYSTEM_PROMPT is not None:
        return _SYSTEM_PROMPT
    raw = PROMPT_PATH.read_text(encoding="utf-8")
    m = re.search(r"## System Prompt\s*\n\n(.*?)\n\n## User Prompt", raw, re.DOTALL)
    if not m:
        raise RuntimeError(f"could not find '## System Prompt' section in {PROMPT_PATH}")
    _SYSTEM_PROMPT = m.group(1).strip()
    return _SYSTEM_PROMPT


def format_context(hits: list[Hit]) -> str:
    return "\n\n".join(f"[{h.chunk_id}] {h.text}" for h in hits)


def generate_answer(question: str, hits: list[Hit], model: str = LLM_MODEL) -> str:
    """Call gpt-4o-mini to answer `question` grounded only in `hits`.

    Returns either a grounded answer, or FALLBACK_TEXT if the model
    determined (via the NO_EVIDENCE_SENTINEL rule in the prompt) that the
    retrieved context doesn't support an answer.
    """
    client = _get_client()
    system_prompt = _load_system_prompt()
    context = format_context(hits)
    user_prompt = f"질문: {question}\n\n제공된 문서 조각:\n{context}"

    resp = client.chat.completions.create(
        model=model,
        temperature=0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    raw_answer = (resp.choices[0].message.content or "").strip()

    if raw_answer == NO_EVIDENCE_SENTINEL:
        return FALLBACK_TEXT
    return raw_answer
